
version: 2
jobs:
  test:
    docker:
      - image: circleci/php:7.1-node-browsers
    working_directory: ~/repo
    steps:

      - run: sudo apt-get install -y libbz2-dev
      - run: sudo docker-php-ext-install bz2
      - run: sudo composer self-update

      - checkout

      # Change the ckeditor http url to https
      # FIXME can we just fix this  so 'composer update' doesnt clobber it once and
      # for all??
      # Or just set secure-http to false? https://getcomposer.org/doc/06-config.md#secure-http
      - run: sed -i 's/http:\/\/download.ckeditor.com/https:\/\/download.ckeditor.com/g' composer.lock

      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/repo

      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.lock" }}
            - composer-v1-

      - run: composer install -n --prefer-dist

      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor

      - run: ./scripts/test.sh
  deploy:
    docker:
      - image: govau/cf-cli
    working_directory: ~/repo
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}

      - run: curl -v -L -o cf-cli_amd64.deb 'https://cli.run.pivotal.io/stable?release=debian64&version=6.33.0&source=github-rel'
      - run: dpkg -i cf-cli_amd64.deb
      - run: cf install-plugin https://github.com/contraband/autopilot/releases/download/0.0.6/autopilot-linux -f

      - run:
          name: Deploying to cloud.gov.au
          command: ./scripts/deploy.sh
workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                # - master
                - develop
                # - tests
