features:
  node_user_picture: true
  comment_user_picture: true
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 0
  path: themes/custom/dta-uikit-base/img/logo.png
favicon:
  use_default: 0
  path: profiles/govcms/favicon.ico
  mimetype: image/vnd.microsoft.icon
