node_title_validation_config:
  comma-blog_post: 0
  exclude-blog_post: ''
  min-blog_post: '1'
  max-blog_post: '65'
  min-wc-blog_post: '1'
  max-wc-blog_post: '25'
  unique-blog_post: 1
  comma-digital_service_standard: 0
  exclude-digital_service_standard: ''
  min-digital_service_standard: '1'
  max-digital_service_standard: '65'
  min-wc-digital_service_standard: '1'
  max-wc-digital_service_standard: '25'
  unique-digital_service_standard: 1
  comma-govcms_event: 0
  exclude-govcms_event: ''
  min-govcms_event: '1'
  max-govcms_event: '65'
  min-wc-govcms_event: '1'
  max-wc-govcms_event: '25'
  unique-govcms_event: 1
  comma-news_item: 0
  exclude-news_item: ''
  min-news_item: '1'
  max-news_item: '65'
  min-wc-news_item: '1'
  max-wc-news_item: '25'
  unique-news_item: 1
  comma-page: 0
  exclude-page: ''
  min-page: '1'
  max-page: '65'
  min-wc-page: '1'
  max-wc-page: '25'
  unique-page: 1
  unique: 1
_core:
  default_config_hash: 5p2lzpRAbNnhbgkvO2MKkxtc2QOBeMRkWubKyc7HYFE
